// export { default as mdx } from './MDX';
export { default as h2 } from './Heading2';
export { default as h3 } from './Heading3';
export { default as h4 } from './Heading4';
export { default as p } from './Paragraph';
export { default as pre } from './Pre';
export { default as code } from './Code';
export { default as blockquote } from './BlockQuote';
export { default as ol } from './OrderedList';
export { default as ul } from './UnorderedList';
export { default as li } from './ListItem';
export { default as a } from './Anchor';
export { default as img } from './Image';
export { default as div } from './Div';
export { default as table } from './Table';
